#!/usr/bin/env bash
# Print text, but acknowledge when unlucky or lucky
i=1
while [ "$i" -le 10 ]; do
	if [ "$i" -eq 4 ]; then
		echo "bad luck"
	elif [ "$i" -eq 8 ]; then
		echo "good luck"
	else 
		echo "Best School"
	fi
	((i++))
done
