#!/usr/bin/env bash
# Print indefinitely and handle interrupts
while true; do
        echo "To infinity and beyond"
        sleep 2
        trap 'echo "I am invincible!!!"' SIGTERM
done

~                                                                                                                                                                                                                                                           
~                      
